[workspace]
resolver = "2"
members = [
    "2025/1",
    "2025/2",
    "2025/3",
    "2025/4",
    "2025/5",
    "2025/6",
    "2025/7",
    "2025/8",
    "2025/9",
    "2025/10",
    "2025/11",
    "2025/12",
]
